# Site Settings
title: Edouard Rossburger | Développeur Front-End
email: edouard.rossburger@gmail.com
description: Edouard Rossburger, développeur Front-End basé à Paris. Vous avez un projet à me confier? Parlons-en!
baseurl: ""
url: "http://localhost:4000"
github_username:  erossburger
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
